services:
  whisper-service:
    build: .
    container_name: whisper-transcription-service
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    volumes:
      # Optional: mount for persistent model cache
      - whisper_cache:/root/.cache/whisper

volumes:
  whisper_cache: